# build
FROM arm64v8/gradle:7.4.2-jdk17 AS builder

RUN mkdir -p /app
WORKDIR /app

COPY . .

ENV GRADLE_OPTS -Dkotlin.compiler.execution.strategy="in-process"

RUN gradle bootJar --no-daemon

FROM arm64v8/adoptopenjdk:16-jre

RUN mkdir /app

COPY --from=builder /app/memoria/build/libs/memoria-0.0.1-SNAPSHOT.jar /app

ENTRYPOINT [                              \
    "java",                               \
    "-jar",                               \
    "/app/memoria-0.0.1-SNAPSHOT.jar"     \
]
