version: '3'

services:
  database:
    image: arm64v8/mysql:oracle
    container_name: reimysql
    environment:
      - MYSQL_DATABASE=memoria
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=1234
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    volumes:
      - /home/yuni/reimysql/memoria:/var/lib/mysql

  application:
    build:
      context: .
      dockerfile: Dockerfile.raspberry
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - database
    container_name: memoria

networks:
  default:
    external:
      name: yunetwork
