version: '3'

services:
  database:
    image: mysql
    container_name: reimysql
    environment:
      - MYSQL_DATABASE=memoria
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=1234
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    volumes:
      - /home/yuni/reimysql/memoria:/var/lib/mysql
    networks:
      - yunetwork

  application:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - database
    container_name: memoria
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/memoria
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - yunetwork

networks:
  yunetwork:
