spring:
  datasource:
    url: jdbc:mysql://database:3306/memoria
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#  mvc:
#    static-path-pattern: /static/**
#    web:
#      resources:
#        static-locations: classpath:/static/
#        add-mappings: true

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3307/memoria

server:
  port: 8081
